# Generated by Django 3.2.7 on 2021-09-25 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schame_name', models.CharField(max_length=250)),
                ('column_separator', models.CharField(choices=[('comma', 'Comma')], default='comma', max_length=20)),
                ('strings_charakters', models.CharField(choices=[('duble-quote', 'Published')], default='comma', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schemas', related_query_name='schema', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schema_columns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('full_name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('company_name', 'Company name'), ('phone_number', 'Phone number'), ('company_name', 'Company name')], default='email', max_length=50)),
                ('order', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', related_query_name='columns', to='dumy.schema')),
            ],
        ),
    ]
