# Generated by Django 3.2.7 on 2021-09-25 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dumy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schemas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schema_columns',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='dumy.schema'),
        ),
    ]
