# Generated by Django 3.2.7 on 2021-09-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumy', '0002_auto_20210925_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schema_columns',
            new_name='Columns',
        ),
    ]
