# Generated by Django 3.2.7 on 2021-09-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumy', '0003_rename_schema_columns_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='schame_name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
