# Generated by Django 3.2.7 on 2021-09-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumy', '0004_alter_schema_schame_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='strings_charakters',
            new_name='string_character',
        ),
    ]
