# Generated by Django 3.2.7 on 2021-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumy', '0005_rename_strings_charakters_schema_string_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='type',
            field=models.CharField(choices=[('full_name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('company_name', 'Company name'), ('phone_number', 'Phone number')], default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[('comma', 'Comma (,)')], default='comma', max_length=20),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('duble-quote', 'Double-quote (“)')], default='duble-quote', max_length=20),
        ),
    ]
