# Generated by Django 3.2.7 on 2021-09-26 17:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dumy', '0006_auto_20210926_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='columns',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['updated']},
        ),
        migrations.AlterUniqueTogether(
            name='columns',
            unique_together={('schema', 'order', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='schema',
            unique_together={('user', 'schame_name')},
        ),
    ]
