# Generated by Django 3.2.7 on 2021-09-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumy', '0007_auto_20210926_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
