# Generated by Django 3.2.7 on 2021-09-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumy', '0008_alter_columns_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='columns',
            unique_together={('schema', 'order'), ('schema', 'name')},
        ),
    ]
